apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: accommodations
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/accommodations
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: accommodations
type: Opaque
data:
  POSTGRES_DB: YWNjb21tb2RhdGlvbnM=
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4=
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=
