name: CI - Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the backend Docker image
      run: docker build ./backend --file ./backend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/accommodations-backend:latest
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the backend Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/accommodations-backend:latest
